name: workflow-test

on: [push]

jobs:
  workflow-job:
    runs-on: ubuntu-latest
    steps:
      - name: "group logging"
        run: |
          echo "::group::Build Details"
          echo "Compiling code..."
          echo "Running internal checks..."
          echo "::endgroup::"
      
      - name: "step 1"
        run: |
          echo "MY_VAL=hello" >> $GITHUB_ENV
      - name: "step 2"
        run: |
          echo "cuurent MY_VAL value is $MY_VAL"

  