name: jobs-demo

on: ["push"]

jobs:
  job1:
    name: "Job 1 (Mac)"
    runs-on: macos-latest
    steps:
      - name: Step b 
        run: echo "Hello macci"

  job2:
    name: "Job 2 (Ubuntu Dependency)"
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: step actions
        run: echo "Hello  ubuntu world"