name: workflow-test

on: [push]

jobs:
  workflow-job:
    runs-on: ubuntu-latest
    steps:
      - name: "group logging"
        run: |
          echo "::group::Build Details"
          echo "Compiling code..."
          echo "Running internal checks..."
          echo "::endgroup::"
  